# Generated by Django 5.2.4 on 2025-07-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
